export const CONST = {
  MINS_PER_HOUR: 60,
  HOURS_PER_DAY: 24,
  DAYS_PER_WEEK: 7,
  DAYS_PER_YEAR: 365,
  ML_PER_LITER: 1000,
} as const;

export const UNITS = {
  minutes: 1,
  hours: 60,
  ml: 1,
  l: 1000,
  generic: 1,
} as const;

export const FUN = {
  RAIN_DROPS_PER_ML: 20,
  AVERAGE_MIN_PER_BOOK_READ: CONST.MINS_PER_HOUR * 15,
  AVERAGE_MIN_PER_BOOK_WRITE:
    CONST.MINS_PER_HOUR * CONST.HOURS_PER_DAY * CONST.DAYS_PER_WEEK,
  CIGARETTES_PER_PACK: 20,
  PRICE_PER_PACK: 6.5,
  HOURS_TO_LEARN_LANGUAGE: 1440 * CONST.MINS_PER_HOUR,
  MINS_WORKING_PROFICIENCY: 700 * CONST.MINS_PER_HOUR,
} as const;
